<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GenericalAPI.Shared\GenericalAPI.Shared.csproj" />
    <ProjectReference Include="..\GenericalAPI.Domain\GenericalAPI.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Abstractions\Persistence\IAuditableEntity.cs" />
  </ItemGroup>

</Project>
